version: "3.8"
services:
  tiktok-downloader:
    build: .
    container_name: tiktok-downloader
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./templates:/app/templates
      - ./instagram_cookies.txt:/app/instagram_cookies.txt
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy: {}
    runtime: nvidia 